#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://chaitanyavaidya:X0Q1B6hKcdKkVndN@cluster0.eanbs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#      database: journal
#      auto-index-creation: true
#
#server:
#  port: 8081
#  servlet:
#    context-path: /journal
